version: 0.2
env:
  secrets-manager:
    SECRET_VALUE: "arn:aws:secretsmanager:us-east-1:358326491230:secret:vikas.env-s03Rwx"
    
phases:
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SRC_DIR_angular
      - pwd
      - ls -al
      - cd $CODEBUILD_SRC_DIR
      - ls -al
      - cd ../$CODEBUILD_SRC_DIR_angular
      - ls -al
      #- |
      #  #!/bin/bash
      #  if [ "$CODEBUILD_SOURCE_REPO_URL" = "https://github.com/vikaskumarp1061/todo-react-app.git" ]; then
      #    pwd
      #    ls -al
          # Copy the secret value into .env file
      #    echo $CODEBUILD_SRC_DIR
      #   echo $SECRET_VALUE >> ${CODEBUILD_SRC_DIR}/.env
      #    ls -al
      #    cat ${CODEBUILD_SRC_DIR}/.env
      #    ls
      #  fi

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - build/**/*
    - .env
