version: 0.2
env:
  variables:
    NODE_VERSION_REACT: "14"
    NODE_VERSION_ANGULAR: "18"
  secrets-manager:
    SECRET_VALUE: "arn:aws:secretsmanager:us-east-1:358326491230:secret:vikas.env-s03Rwx"
    
phases:
  install:
    commands: |-
      if [ "$APPLICATION_TYPE" = "react" ]; then
        nvm install $NODE_VERSION_REACT
        nvm use $NODE_VERSION_REACT
        node -v
      elif [ "$APPLICATION_TYPE" = "angular" ]; then
        # Switch to Node.js version for Angular
        nvm install $NODE_VERSION_ANGULAR
        nvm use $NODE_VERSION_ANGULAR
      fi
      # Install dependencies
      npm install

      
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SRC_DIR_angular
      - pwd
      - ls -al

      
      # Move to React folder
      - cd $CODEBUILD_SRC_DIR
      - |-
          if [ "$APPLICATION_TYPE" = "react" ]; then
            echo "Building React application..."
            npm run build
            ls -al
            mv build todo
          
          elif [ "$APPLICATION_TYPE" = "angular" ]; then
            echo "Building Angular application..."
            cd $CODEBUILD_SRC_DIR_angular
            ng build
            mv dist angular
          fi
      

      
      #  #!/bin/bash
      #  if [ "$CODEBUILD_SOURCE_REPO_URL" = "https://github.com/vikaskumarp1061/todo-react-app.git" ]; then
      #    pwd
      #    ls -al
          # Copy the secret value into .env file
      #    echo $CODEBUILD_SRC_DIR
      #   echo $SECRET_VALUE >> ${CODEBUILD_SRC_DIR}/.env
      #    ls -al
      #    cat ${CODEBUILD_SRC_DIR}/.env
      #    ls
      #  fi

artifacts:
  files:
    - todo/**/*
    - angular/**/*
    - appspec.yml
    - scripts/**/*
    - .env
