version: 0.2
env:
  secrets-manager:
    SECRET_VALUE: "arn:aws:secretsmanager:us-east-1:358326491230:secret:vikas.env-s03Rwx"
    
phases:
  install:
    runtime-versions:
      nodejs: 14
   
       
  build:
    commands:

        - pwd
        - ls -al
         # copy the secret value in .env file
        - cat $CODEBUILD_SRC_DIR
        - echo $SECRET_VALUE >>${CODEBUILD_SRC_DIR}/.env
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - build/**/*
